version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
      weekly-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
      weekly-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
