"""create_generated_documents_table

Revision ID: 36e251d219a0
Revises: 535273772ad1
Create Date: 2026-04-15 18:01:47.590482

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36e251d219a0"
down_revision: str | Sequence[str] | None = "535273772ad1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_documents",
        sa.Column("access_grant_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("generated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_format", sa.String(length=10), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["access_grant_id"], ["access_grants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generated_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_documents_access_grant_id"),
        "generated_documents",
        ["access_grant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_documents_generated_by_user_id"),
        "generated_documents",
        ["generated_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_documents_template_id"),
        "generated_documents",
        ["template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_documents_template_id"), table_name="generated_documents")
    op.drop_index(
        op.f("ix_generated_documents_generated_by_user_id"), table_name="generated_documents"
    )
    op.drop_index(op.f("ix_generated_documents_access_grant_id"), table_name="generated_documents")
    op.drop_table("generated_documents")
    # ### end Alembic commands ###
